export const InspectorMessageIds = {
	RUNTIME: {
		RUN_IF_WAITING_FOR_DEBUGGER: 11,
		GET_MEMORY_USAGE: 12,
		GLOBAL_LEXICAL_SCOPE_NAMES: 13,
		EVALUATE_EXPRESSION: 14,
	},
	DEBUGGER: {
		ENABLE: 21,
		PAUSE: 22,
		RESUME: 23,
		GET_SCRIPT_SOURCE: 24,
		SET_BREAKPOINT: 25,
		SET_BREAKPOINT_BY_URL: 26,
	},
};
