import { app, BrowserWindow, ipcMain } from "electron";
import { spawn, ChildProcessWithoutNullStreams } from "node:child_process";
import path from "path";
import pidusage from "pidusage";
import {
    PROCESS_LOG,
    START_SUBPROCESS,
    TERMINATE_SUBPROCESS,
} from "./constants";
import { passMessage } from "./logger";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let subprocess: ChildProcessWithoutNullStreams;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

let mainWindow: BrowserWindow;

const createWindow = (): void => {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    //  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

const isProcessRunning = (): boolean => {
    return !subprocess?.killed && subprocess?.exitCode === null;
};

ipcMain.on(START_SUBPROCESS, () => {
    if (isProcessRunning()) {
        mainWindow.webContents.send(
            PROCESS_LOG,
            passMessage("process already running")
        );
    } else {
        mainWindow.webContents.send(
            PROCESS_LOG,
            passMessage("starting and external process")
        );
        subprocess = spawn("node", [
            path.normalize("C:\\Users\\ASUS\\Desktop\\nest_app\\dist\\main.js"),
        ]);

        pidusage(subprocess.pid, (_, stats) => {
            console.log(stats);
        });

        subprocess.stdout.on("data", (data) => {
            mainWindow.webContents.send(PROCESS_LOG, data.toString());
        });

        subprocess.stderr.on("data", (data) => {
            mainWindow.webContents.send(
                PROCESS_LOG,
                `ERROR: ${data.toString()}`
            );
        });

        subprocess.on("exit", (code) => {
            mainWindow.webContents.send(
                PROCESS_LOG,
                passMessage(`Process exited with code ${code}`)
            );
        });
    }
});

ipcMain.on(TERMINATE_SUBPROCESS, () => {
    if (!subprocess.killed && subprocess.exitCode == null) {
        mainWindow.webContents.send(
            PROCESS_LOG,
            passMessage("terminating the process")
        );
        subprocess.kill();
    } else {
        mainWindow.webContents.send(
            PROCESS_LOG,
            passMessage("process isnt running")
        );
    }
});
