name: Build Electron App

on:
  push:
    branches: 
        - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
         node-version: 20
         cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install


      - name: Run Build
        run: pnpm exec electron-builder --windows nsis:ia32

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: out/
