name: Build Electron App

on:
  push:
    branches: 
        - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
         node-version: 20

      - name: Install dependencies
        run: yarn install
        shell: pwsh
    
      - name: Package
        run: yarn package
        shell: pwsh

      - name: Build
        run: yarn dist
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: dist/
